version: "3"

services:
  consul1:
    command: "agent -server -bootstrap -ui -client 0.0.0.0"
    image: consul:latest
    networks:
      - "consul"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    restart: "always"
    volumes:
      - "./data/consul/1:/consul/data"
  consul2:
    command: "agent -server -retry-join consul1 -client 0.0.0.0"
    depends_on:
      - "consul1"
    image: consul:latest
    networks:
      - "consul"
    restart: "always"
    volumes:
      - "./data/consul/2:/consul/data"
  postgres:
    environment: 
      POSTGRES_PASSWORD: "mu2"
      POSTGRES_USER: "mu2"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    image: "postgres:latest"
    networks:
      - "db"
    restart: "always"
    # volumes:
    #   - "./data/postgres:/var/lib/postgresql/data/pgdata"
  search:
    build: ./mu2-search
    command: ./mu2-search --consul-addr=consul1:8500
    depends_on:
      - "consul1"
      - "consul2"
    networks:
      - "consul"
      - "search"
    restart: "always"
  encode:
    build: ./mu2-encode
    command: ./mu2-encode --consul-addr=consul1:8500
    depends_on:
      - "consul1"
      - "consul2"
    networks:
      - "consul"
      - "encode"
    restart: "always"
  bot:
    build: ./mu2
    command: ./mu2 --consul-addr=consul1:8500
    depends_on:
      - "consul1"
      - "consul2"
      - "postgres"
      - "search"
      - "encode"
    environment:
      - MU2_CONSUL_ADDRESS=consul1:8500
    networks:
      - "consul"
      - "db"
      - "search"
      - "encode"
    restart: "always"

networks:
  consul:
  db:
  search:
  encode:
